name: ServerUI
main: ServerUI\Main
api: [3.0.0, 3.1.0, 3.2.0, 3.3.0, 3.9.0, 3.9.1, 3.9.2, 3.9.3, 3.9.4, 3.9.5, 3.9.6, 3.9.7, 3.9.8, 4.0.0]
version: 1.0
author: zJustMarcel

commands:
 serverui:
  description: "Open ServerUI"
